### ISSUE TITLE
display cloud AI APIs enabled

### ISSUE THREAD

**Issue by forrestbao** [TexteaInc/LlaMasterKey#4]
Here is a feature request. 

It would be better to display which cloud AI APIs can be handled by an LMK server instance. This can help server admin be aware of the status of the LMK server instance. 

In addition, in the example below, no cloud API has been enabled. So the message should reflect that the LMK server cannot communicate with any cloud API. 

```
$ ./lmk
 WARN  lmk::state > Please tell your clients to set the following environment variables before
running their code using the Python SDK of OpenAI/Cohere/etc.:

For convenience, the shell command to set such environment variables are
written to `./llamakey_local.env`. Simply run `source ./llamakey_local.env`
to activate them.
For example:
source ./llamakey_local.env && python3 -c "import openai; openai.Completion.create(...)"

 INFO  lmk        > Serve server at: 127.0.0.1:8000
```

**Comment by forrestbao** [comment]
Here is an extended request for this feature request. 
Can we display the masked API keys and the Base URL to help admins have a better awareness of the system status? 

Thus, instead of this 
```
 INFO  lmk::state > API endpoints availability:
✓ OpenAI
✓ Cohere
✓ Anyscale
```
, please display 
```
 INFO  lmk::state > API endpoints availability:
✓ OpenAI  using base URL https://api.openai.com/v1 and key openai-**********23xe3
✓ Cohere  using base URL xxxxxxxxxx and key co-**********3ffx1
✓ Anyscale using  base URL  xxxxxxxxxx and key an-**********x8wqw
```

The reason I have this request is because I just started an LMK server in a terminal where the Base URLs and API keys are meant for another LMK server.

**Comment by Colerar** [comment]
Now the message looks like:

<img width="1119" alt="image" src="https://github.com/TexteaInc/LlaMasterKey/assets/62297254/905f4d83-6c90-4aac-af85-48d2e9bb8e32">
